#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the breakingRecords function below.
def breakingRecords(scores):
    high_score= 0
    low_score = 0
    highest = scores[0]
    lowest = scores[0]
    for i in range(1, len(scores)):
        if lowest > scores[i]:
            lowest = scores[i]
            low_score +=1
        elif highest < scores[i]:
            highest = scores[i]
            high_score +=1
    return high_score, low_score
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
