#!/bin/python3

import math
import os
import random
import re
import sys

def diagonalDifference(arr):
    sum_diog1 = 0
    sum_diog2 = 0
    for i in range(n):
        sum_diog1 += arr[i][i]
        sum_diog2 += arr[i][n-i-1]

    return abs(sum_diog1 - sum_diog2)
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
  
