#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.  
def miniMaxSum(arr):
   sum_max = 0
   sum_min = 0
   arr.sort()
   for i in range(0,4,1):
     sum_min += arr[i]
   for i in range(1,5,1):
     sum_max += arr[i]
   print(sum_min, sum_max)

if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
